### ISSUE TITLE
Add accounts tab with remote paginated list of all pooling accounts

### ISSUE THREAD

**Issue by felixbrucker** [foxypool/chia-og-pool-ui#9]

**Comment by jRazz** [comment]
Excellent Idea. I like this a lot.

**Comment by jRazz** [comment]
Yes! In Progress. Less gooooo~!!

(Am I allowed to be your cheer squad? )  😄

**Comment by felixbrucker** [comment]
Closed by https://github.com/foxypool/chia-og-pool-ui/commit/374ed9ac3439fe6a7ab232388839b9ccd8ece413
